# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - swan-river-group-project

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          #client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6BAD3FA66D474E4D8139188DC94B6D9F }}
          #tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_589EA075831547DCBD7DE008E84013F8 }}
          #subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3F6A946AE2D94AD083A9A7E623A00291 }}
          subscription-id: 91752863-c2fa-4d1e-944e-262a3c7c5a39
          client-id: f435d3c1-426e-4490-80c4-ac8ff8c05574
          tenant-id: 170bbabd-a2f0-4c90-ad4b-0e8f0f0c4259
          #allow-no-subscriptions: true

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'swan-river-group-project'
          slot-name: 'production'
          
